/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RESERVA_BOL_H_RPCGEN
#define _RESERVA_BOL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct seat {
	int rowno;
	int colno;
};
typedef struct seat seat;

#define RESERVA_BOL_PROG 0x31111111
#define RESERVA_BOL_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define RESERVE 1
extern  int * reserve_1(seat *, CLIENT *);
extern  int * reserve_1_svc(seat *, struct svc_req *);
#define ROWS 2
extern  int * rows_1(void *, CLIENT *);
extern  int * rows_1_svc(void *, struct svc_req *);
#define COLS 3
extern  int * cols_1(void *, CLIENT *);
extern  int * cols_1_svc(void *, struct svc_req *);
#define LISTFREE 4
extern  char ** listfree_1(void *, CLIENT *);
extern  char ** listfree_1_svc(void *, struct svc_req *);
extern int reserva_bol_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RESERVE 1
extern  int * reserve_1();
extern  int * reserve_1_svc();
#define ROWS 2
extern  int * rows_1();
extern  int * rows_1_svc();
#define COLS 3
extern  int * cols_1();
extern  int * cols_1_svc();
#define LISTFREE 4
extern  char ** listfree_1();
extern  char ** listfree_1_svc();
extern int reserva_bol_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_seat (XDR *, seat*);

#else /* K&R C */
extern bool_t xdr_seat ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RESERVA_BOL_H_RPCGEN */
